//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieITDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seance
    {
        public System.Guid SeanceGuid { get; set; }
        public Nullable<System.Guid> MovieGuid { get; set; }
        public Nullable<System.Guid> CinemaGuid { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
